export const sqlite_sqls = [
  `CREATE TABLE jbjl_cl_jcsj (
    bh       VARCHAR (40)  NOT NULL,
    n        VARCHAR (40),
    y        VARCHAR (40),
    r        VARCHAR (40),
    rwbh     VARCHAR (40),
    zrwbh    VARCHAR (40),
    jgbh     VARCHAR (40),
    sjmc     VARCHAR (40),
    jcsj     DATETIME (6),
    jcdd     VARCHAR (40),
    jcddjwd  VARCHAR (40),
    cphm     VARCHAR (40),
    cx       VARCHAR (40),
    fdjbh    VARCHAR (40),
    ys       VARCHAR (40),
    cjh      VARCHAR (40),
    dw       VARCHAR (40),
    wgtz     VARCHAR (40),
    jsyxm    VARCHAR (40),
    jsyxb    VARCHAR (40),
    jsyzjlx  VARCHAR (40),
    jsyzjhm  VARCHAR (40),
    csdwbm   VARCHAR (40),
    sjlx     VARCHAR (40),
    wjwfqx   VARCHAR (512),
    czqk     VARCHAR (518),
    jcrybh   VARCHAR (40),
    sjjlsj   DATE,
    sm       VARCHAR (50),
    gzcljg   VARCHAR (40),
    gzclsj   VARCHAR (40),
    zhgxsj   DATE,
    zhgxrybh VARCHAR (40),
    yzbs     INTEGER,
    ssdwmc   VARCHAR (128),
    jz       VARCHAR (40),
    lxfs     VARCHAR (40),
    clssdwmc VARCHAR (50),
    userid   VARCHAR (40)  NOT NULL,
    sync     VARCHAR (40)  DEFAULT 0,
    wjwfqxbh VARCHAR (128),
    sqlzsc   VARCHAR (40),
    csny     VARCHAR (40),
    czbh     VARCHAR (40),
    jx       VARCHAR (40),
    zw       VARCHAR (40),
    zd       VARCHAR (40) 
  );`,
  `CREATE TABLE jbjl_czff (
    bh   VARCHAR (40),
    zcmc VARCHAR (50),
    tm   VARCHAR (50),
    kx   VARCHAR (50),
    lx   VARCHAR (40),
    qxms VARCHAR (500),
    qxjc VARCHAR (100),
    czff VARCHAR (500),
    yzcd VARCHAR (50),
    klwp VARCHAR (100),
    yzbs VARCHAR (50) 
);
`,
  `CREATE TABLE jbjl_dic (
    bh INTEGER      NOT NULL,
    mc VARCHAR (40),
    lx VARCHAR (40),
    UNIQUE (
        bh DESC
    )
);
`,
  `CREATE TABLE jbjl_fj (
    bh         VARCHAR (40)  NOT NULL,
    filename   VARCHAR (128),
    fileurl    VARCHAR (40),
    createtime [DATE TIME],
    createuser VARCHAR (40),
    sjbh       VARCHAR (40) 
);
`,
  `CREATE TABLE jbjl_jm_jcsj (
    bh       VARCHAR (40) NOT NULL,
    n        VARCHAR (40),
    y        VARCHAR (40),
    r        VARCHAR (40),
    rwbh     VARCHAR (40),
    zrwbh    VARCHAR (40),
    jgbh     VARCHAR (40),
    sjmc     VARCHAR (40),
    ckclhp   VARCHAR (40),
    dyzshpdw VARCHAR (40),
    jcsj     [DATE TIME],
    jcdd     VARCHAR (40),
    jcddjwd  VARCHAR (40),
    jsyxm    VARCHAR (40),
    jsyxb    VARCHAR (40),
    jsycsny  VARCHAR (40),
    jsyzz    VARCHAR (40),
    jsylxdh  VARCHAR (40),
    jsyjg    VARCHAR (40),
    jsyzjlx  VARCHAR (40),
    jsyzjhm  VARCHAR (40),
    clcx     VARCHAR (40),
    clys     VARCHAR (40),
    cldfhp   VARCHAR (40),
    cldfdjh  VARCHAR (40),
    clywhfly VARCHAR (40),
    clcjh    VARCHAR (40),
    wfwt     VARCHAR (40),
    czyj     VARCHAR (40),
    jcrybh   VARCHAR (40),
    cbyj     VARCHAR (40),
    sjjlsj   [DATE TIME],
    psrybh   VARCHAR (40),
    szpsnr   VARCHAR (40),
    szpssj   [DATE TIME],
    gzczjg   VARCHAR (40),
    gzczsj   [DATE TIME],
    gzczyj   VARCHAR (50),
    yzbs     INTEGER,
    sm       VARCHAR (40),
    sfkl     VARCHAR (40),
    userid   VARCHAR (40) NOT NULL,
    sync     VARCHAR (40) DEFAULT 0,
    jsyssdw  VARCHAR (40),
    sfjr     VARCHAR (40),
    dyzshp   VARCHAR (40)
);
`,
  `CREATE TABLE jbjl_jm_jsdw (
    bh       VARCHAR (40) NOT NULL,
    n        VARCHAR (40),
    y        VARCHAR (40),
    r        VARCHAR (40),
    rwbh     VARCHAR (40),
    zrwbh    VARCHAR (40),
    jgbh     VARCHAR (40),
    sjmc     VARCHAR (40),
    jcsj     [DATE TIME],
    jcdd     VARCHAR (40),
    jcddjwd  VARCHAR (40),
    bjmdwmc  VARCHAR (40),
    bjmdwfzr VARCHAR (40),
    fzrzz    VARCHAR (40),
    fzrzjlx  VARCHAR (40),
    fzrzjhm  VARCHAR (40),
    fzrjg    VARCHAR (40),
    fzrlxfs  VARCHAR (40),
    wfwt     VARCHAR (40),
    czyj     VARCHAR (40),
    jcrybh   VARCHAR (40),
    sjjlsj   [DATE TIME],
    cbyj     VARCHAR (40),
    psrybh   VARCHAR (40),
    szpsnr   VARCHAR (40),
    szpssj   [DATE TIME],
    gzczjg   VARCHAR (40),
    gzczsj   [DATE TIME],
    gzczyj   VARCHAR (40),
    yzbs     INTEGER,
    sm       VARCHAR (40),
    hy       VARCHAR (40),
    jmdwfzr  VARCHAR (40),
    jmdwmc   VARCHAR (40),
    userid   VARCHAR (40) NOT NULL,
    sync     VARCHAR (40) DEFAULT 0,
    sfjr   VARCHAR (40),
    sfkl   VARCHAR (40)
);`,
  `CREATE TABLE jbjl_jr_jmsj (
    bh       VARCHAR (40) NOT NULL,
    n        VARCHAR (40),
    y        VARCHAR (40),
    r        VARCHAR (40),
    rwbh     VARCHAR (40),
    zrwbh    VARCHAR (40),
    jgbh     VARCHAR (40),
    sjmc     VARCHAR (40),
    jcsj     [DATE TIME],
    jcdd     VARCHAR (40),
    jcddjwd  VARCHAR (40),
    xm       VARCHAR (40),
    xb       VARCHAR (40),
    csny     VARCHAR (40),
    zz       VARCHAR (40),
    lxdh     VARCHAR (40),
    jg       VARCHAR (40),
    zjlx     VARCHAR (40),
    zjhm     VARCHAR (40),
    wfwt     VARCHAR (40),
    czyj     VARCHAR (40),
    jcrybh   VARCHAR (40),
    cbyj     VARCHAR (40),
    sjjlsj   [DATE TIME],
    psrybh   VARCHAR (40),
    szpsnr   VARCHAR (50),
    szpssj   [DATE TIME],
    gzczjg   VARCHAR (40),
    gzczsj   [DATE TIME],
    gzczyj   VARCHAR (40),
    sm       VARCHAR (40),
    zhgxsj   [DATE TIME],
    zhgxrybh VARCHAR (40),
    yzbs     INTEGER,
    zy       VARCHAR (40),
    sjycd    VARCHAR (40),
    sfkl     VARCHAR (40),
    kllx     INTEGER,
    userid   VARCHAR (40) NOT NULL,
    sync     VARCHAR (40) DEFAULT 0,
    jmrssdw  VARCHAR (40),
    sfjr     VARCHAR (40)
);
`,
  `CREATE TABLE jbjl_ry_jcsj (
    bh       VARCHAR (40)  NOT NULL,
    n        VARCHAR (40),
    y        VARCHAR (40),
    r        VARCHAR (40),
    rwbh     VARCHAR (40),
    zrwbh    VARCHAR (40),
    jgbh     VARCHAR (40),
    sjmc     VARCHAR (40),
    jcsj     DATETIME,
    jcdd     VARCHAR (40),
    jcddjwd  VARCHAR (40),
    xm       VARCHAR (40),
    xb       VARCHAR (40),
    nl       INTEGER,
    zjlx     VARCHAR (40),
    zjhm     VARCHAR (40),
    ssdwbm   VARCHAR (40),
    sjlx     INTEGER,
    wjwfqx   VARCHAR (100),
    czqk     VARCHAR (100),
    jcrybh   VARCHAR (40),
    sjjlsj   [DATE TIME],
    sm       VARCHAR (40),
    gzcljg   VARCHAR (40),
    gzclsj   [DATE TIME],
    zhgxsj   DATE,
    zhgxrybh VARCHAR (40),
    yzbs     INTEGER,
    yj       VARCHAR (40),
    jx       VARCHAR (40),
    zw       VARCHAR (40),
    zy       VARCHAR (40),
    sjycd    VARCHAR (40),
    lxfs     VARCHAR (40),
    zd       VARCHAR (128),
    jz       VARCHAR (40),
    ssdwmc   VARCHAR (128),
    userid   VARCHAR (40)  NOT NULL,
    sync     VARCHAR (40)  DEFAULT 0,
    wjwfqxbh VARCHAR (128),
    sqlzsc   VARCHAR (40),
    czbh     VARCHAR (40),
    csny     VARCHAR (40) 
);
`,
  `CREATE TABLE jbjl_txl (
  userid VARCHAR (40) PRIMARY KEY UNIQUE NOT NULL,
  list   VARCHAR (1024) 
);
`,
  `CREATE TABLE jbjl_history_msg (
  sendId    VARCHAR (40),
  receiveId VARCHAR (40),
  message   VARCHAR (40),
  fromUser  VARCHAR (40),
  time      VARCHAR (40)
);
`,
  `CREATE TABLE XXSZ (
    id     VARCHAR (40),
    status VARCHAR (40) 
);
`
];

export const dic_data = [
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (3, '求援', '0');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (2, '严重', '0');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (1, '一般', '0');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (10, '军人保障卡证', '1');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (9, '护照', '1');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (8, '身份证', '1');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (7, '文职人员证', '1');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (6, '军官证', '1');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (5, '士官证', '1');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (4, '义务兵证', '1');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (11, '上将', '2');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (14, '大校', '2');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (13, '少将', '2');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (12, '中将', '2');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (30, '上等兵', '2');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (29, '列兵', '2');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (28, '下士', '2');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (27, '中士', '2');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (26, '上士', '2');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (25, '四级军士长', '2');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (24, '三级军士长', '2');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (23, '二级军士长', '2');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (22, '一级军士长', '2');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (21, '少尉', '2');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (20, '中尉', '2');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (19, '上尉', '2');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (18, '上尉', '2');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (17, '少校', '2');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (16, '中校', '2');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (15, '上校', '2');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (38, '不确定', '3');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (37, '后勤部队', '3');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (36, '武警部队', '3');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (35, '战略支援部队', '3');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (34, '火箭军', '3');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (33, '空军', '3');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (32, '海军', '3');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (31, '陆军', '3');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (39, '小学', '5');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (40, '初中', '5');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (41, '高中', '5');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (42, '大专', '5');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (44, '硕士', '5');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (43, '本科', '5');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (45, '博士', '5');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (46, '博士后', '5');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (47, '其他', '5');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (48, '军委主席', '6');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (49, '副主席级', '6');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (50, '大军区司令员', '6');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (51, '政治委员级', '6');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (52, '军委委员级', '6');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (53, '正兵团级', '6');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (54, '副兵团级', '6');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (55, '准兵团级', '6');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (56, '正军级', '6');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (57, '副军级', '6');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (58, '准军级', '6');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (59, '正师级', '6');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (60, '副师级', '6');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (61, '准师级', '6');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (66, '副营级', '6');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (65, '正营级', '6');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (64, '准团级', '6');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (63, '副团级', '6');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (62, '正团级', '6');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (72, '正班级', '6');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (71, '副班级', '6');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (70, '副排级', '6');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (69, '正排级', '6');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (68, '副连级', '6');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (67, '正连级', '6');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (73, '战士', '6');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (138, '其他军车违纪违法情节恶劣的', '9');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (139, '专业1', '4');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (137, '涉嫌利用军车进行走私、贩毒、盗抢等违法活动的', '9');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (136, '利用军车从事营业性运输活动或者帮助他人运送物品收取酬劳的', '9');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (135, '车况不良或者违反乘载规定，危及行车安全的', '9');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (134, '酒驾醉驾、毒驾或者涉嫌交通肇事逃逸的', '9');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (133, '未悬挂车辆号牌或者使用过期号牌、非制式号牌的', '9');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (132, '行车执照与车辆、号牌信息不符的', '9');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (131, '无证驾驶或者车辆无行车执照的', '9');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (130, '其他军车违纪违法情节严重的', '9');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (129, '违反规定安装或者使用警报器、警灯的', '9');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (128, '所驾驶车辆与驾驶证准驾车型不符的', '9');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (127, '无车辆派遣凭证，私自出车的', '9');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (126, '其他军车违纪违法情节较轻的', '9');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (125, '摩托车驾乘人员未按规定戴安全头盔的', '9');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (124, '未携带三角警告牌、处于有效期内的灭火器等驾驶安全设施', '9');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (123, '试车未悬挂试车号牌或者拖挂车未悬挂拖挂车号牌的', '9');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (122, '实习驾驶员不按照规定驾驶机动车的', '9');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (121, '其他军车违纪违法情节轻微且能够现场纠正的', '9');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (120, '违反道路交通安全法规停放车辆的', '9');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (119, '车辆行驶中驾驶员拨打、接听手持电话的', '9');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (118, '驾乘人员在车辆行驶中未按规定使用安全带的', '9');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (117, '驾驶室前后挡风玻璃范围内悬挂、摆放物品的', '9');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (116, '军容不整的', '9');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (115, '其他违纪违法情节严重的', '9');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (114, '在接受检查纠察时拒不出示证件或者以侮辱、谩骂、殴打等方式妨碍警备工作人员执勤的', '9');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (113, '参与不健康消费娱乐活动的', '9');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (112, '携带、观看、传播、制作、贩卖淫秽物品的', '9');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (111, '出租、出售军用牌证或者私自变卖军用物资的', '9');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (110, '违反规定携带易燃、易爆危险物品或者管制刀具的', '9');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (109, '违法规定携带武器、弹药或者其他军用物资的', '9');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (108, '打击斗殴、酗酒滋事等扰乱公共秩序的', '9');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (107, '其他违反军容风纪情节较重的', '9');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (106, '未随身携带军队人员身份证件的', '9');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (105, '猥集接头、嬉笑打闹、举止不端的', '9');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (104, '穿鞋、袜不符合规定或者穿拖鞋、赤脚穿鞋的', '9');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (103, '头发和胡须不符合规定或者化浓妆、染指甲的', '9');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (102, '外着制式毛衣（绒衣）的', '9');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (101, '使用非制式腰带、领带、围巾的', '9');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (100, '军服（文职人员服装）与便服混穿或者着仿制军服（文职人员服装）的', '9');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (99, '标志服饰佩戴与本人身份不符或者不齐全的', '9');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (98, '未配套穿着军服（文职人员服装）、不戴军帽（文职人员帽）的', '9');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (97, '其他违反军容风纪情节轻微且能够现场纠正的', '9');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (96, '在公共场所和其他禁止吸烟的场所吸烟，边走边吸烟、吃东西、扇扇子的', '9');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (95, '穿作战靴系带未扎紧塞入靴内或者着作训服裤口未扣紧塞入靴内的', '9');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (94, '在非雨雪天打伞或者使用非黑色雨伞的', '9');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (93, '戴耳环、项链、领饰、戒指、手镯（链、串）、装饰性头饰等的', '9');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (92, '在外露的腰带上系挂钥匙和饰物的', '9');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (91, '袖手、背手、手插衣袋或者搭肩挽臂的', '9');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (90, '挽袖（着夏作训服时除外）、披衣、敞怀、卷裤腿的', '9');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (89, '着夏常服上衣或者冬常服、春秋常服时衬衣(内衣)下摆未扎于裤内的', '9');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (88, '内着毛衣、绒衣、绒背心、棉衣等下摆外露的', '9');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (87, '不按照规定扣衣扣、拉拉链的', '9');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (86, '戴军帽(文职人员帽)、围制式围巾不符合规定的', '9');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (85, '标志服饰的缀钉不符合规定的', '9');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (84, '故意遮挡、污损、不按规定安装号牌的', '9');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (83, '车辆喷涂、安装、张贴规定以外标志', '9');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (82, '围观和参与社会游行、示威、静坐', '9');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (81, '参与宗教、迷信活动的', '9');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (80, '违反规定占用公交车道，占用应急车道和非机动车道的', '9');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (79, '驾驶证、行车执照无审验合格戳记的', '9');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (78, '通报批评', '8');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (77, '现场纠正', '8');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (76, '扣留车辆', '8');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (75, '盘问留置', '8');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (74, '扣留驾驶证', '8');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (146, '部队5', '10');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (145, '部队4', '10');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (144, '部队3', '10');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (143, '部队2', '10');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (142, '部队1', '10');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (141, '专业3', '4');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (140, '专业2', '4');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (160, '无业', '11');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (159, '行政人员', '11');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (158, '个体经营户', '11');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (157, '警察', '11');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (156, '司机', '11');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (155, '厨师', '11');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (154, '设计师', '11');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (153, '金融', '11');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (152, '政府职员', '11');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (151, 'IT', '11');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (150, '工人', '11');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (149, '军人', '11');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (148, '医生', '11');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (147, '教师', '11');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (161, '货车', '12');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (162, '客车', '12');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (164, '其他', '12');`,
  `INSERT INTO jbjl_dic (bh, mc, lx) VALUES (163, '小车', '12');`
];

export const czff_data = [
  `INSERT INTO jbjl_czff (bh, zcmc, tm, kx, lx, qxms, qxjc, czff, yzcd, klwp, yzbs) VALUES ('2601', '军队警备条令', '二十六', '一', '0', '标志服饰的缀钉不符合规定', NULL, '批评教育，责令立即纠正', '情节轻微', NULL, '0');`,
  `INSERT INTO jbjl_czff (bh, zcmc, tm, kx, lx, qxms, qxjc, czff, yzcd, klwp, yzbs) VALUES ('2602', '军队警备条令', '二十六', '二', '0', '戴军帽（文职人员帽）、围制式围巾不符合规定', NULL, '批评教育，责令立即纠正', '情节轻微', NULL, '0');`,
  `INSERT INTO jbjl_czff (bh, zcmc, tm, kx, lx, qxms, qxjc, czff, yzcd, klwp, yzbs) VALUES ('2603', '军队警备条令', '二十六', '三', '0', '不按规定扣衣扣、拉拉链', NULL, '批评教育，责令立即纠正', '情节轻微', NULL, '0');`,
  `INSERT INTO jbjl_czff (bh, zcmc, tm, kx, lx, qxms, qxjc, czff, yzcd, klwp, yzbs) VALUES ('2604', '军队警备条令', '二十六', '四', '0', '内着毛衣、绒衣、绒背心、棉衣等下摆外露', NULL, '批评教育，责令立即纠正', '情节轻微', NULL, '0');`,
  `INSERT INTO jbjl_czff (bh, zcmc, tm, kx, lx, qxms, qxjc, czff, yzcd, klwp, yzbs) VALUES ('2605', '军队警备条令', '二十六', '五', '0', '着夏常服上衣或者冬常服、春秋常服时衬衣（内衣）下摆未扎于裤内', NULL, '批评教育，责令立即纠正', '情节轻微', NULL, '0');`,
  `INSERT INTO jbjl_czff (bh, zcmc, tm, kx, lx, qxms, qxjc, czff, yzcd, klwp, yzbs) VALUES ('2606', '军队警备条令', '二十六', '六', '0', '挽袖（着夏作训服时除外）、披衣、敞怀、卷裤腿', NULL, '批评教育，责令立即纠正', '情节轻微', NULL, '0');`,
  `INSERT INTO jbjl_czff (bh, zcmc, tm, kx, lx, qxms, qxjc, czff, yzcd, klwp, yzbs) VALUES ('2607', '军队警备条令', '二十六', '七', '0', '袖手、背手、手插衣袋或者搭肩挽臂', NULL, '批评教育，责令立即纠正', '情节轻微', NULL, '0');`,
  `INSERT INTO jbjl_czff (bh, zcmc, tm, kx, lx, qxms, qxjc, czff, yzcd, klwp, yzbs) VALUES ('2608', '军队警备条令', '二十六', '八', '0', '在外露的腰带上系挂钥匙和饰物', NULL, '批评教育，责令立即纠正', '情节轻微', NULL, '0');`,
  `INSERT INTO jbjl_czff (bh, zcmc, tm, kx, lx, qxms, qxjc, czff, yzcd, klwp, yzbs) VALUES ('2609', '军队警备条令', '二十六', '九', '0', '戴耳环、项链、领饰、戒指、手镯（链、串）、装饰性头饰等', NULL, '批评教育，责令立即纠正', '情节轻微', NULL, '0');`,
  `INSERT INTO jbjl_czff (bh, zcmc, tm, kx, lx, qxms, qxjc, czff, yzcd, klwp, yzbs) VALUES ('2610', '军队警备条令', '二十六', '十', '0', '在非雨雪天打伞或者使用非黑色雨伞', NULL, '批评教育，责令立即纠正', '情节轻微', NULL, '0');`,
  `INSERT INTO jbjl_czff (bh, zcmc, tm, kx, lx, qxms, qxjc, czff, yzcd, klwp, yzbs) VALUES ('2611', '军队警备条令', '二十六', '十一', '0', '穿作战靴系带未扎紧塞入靴内或者着作训服裤口未扣紧塞入靴内的', NULL, '批评教育，责令立即纠正', '情节轻微', NULL, '0');`,
  `INSERT INTO jbjl_czff (bh, zcmc, tm, kx, lx, qxms, qxjc, czff, yzcd, klwp, yzbs) VALUES ('2612', '军队警备条令', '二十六', '十二', '0', '在公共场所和其他禁止吸烟的场所吸烟，边走边吸烟、吃东西、扇扇子', NULL, '批评教育，责令立即纠正', '情节轻微', NULL, '0');`,
  `INSERT INTO jbjl_czff (bh, zcmc, tm, kx, lx, qxms, qxjc, czff, yzcd, klwp, yzbs) VALUES ('2613', '军队警备条令', '二十六', '十三', '0', '其他违反军容风纪情节轻微且能够现场纠正', NULL, '批评教育，责令立即纠正', '情节轻微', NULL, '0');`,
  `INSERT INTO jbjl_czff (bh, zcmc, tm, kx, lx, qxms, qxjc, czff, yzcd, klwp, yzbs) VALUES ('2701', '军队警备条令', '二十七', '一', '0', '未配套穿着军服（文职人员服装）、不戴军帽（文职人员帽）', NULL, '批评教育，开具《军队人员（车辆）违纪违法通知单》后放行', '情节较重', NULL, '2');`,
  `INSERT INTO jbjl_czff (bh, zcmc, tm, kx, lx, qxms, qxjc, czff, yzcd, klwp, yzbs) VALUES ('2702', '军队警备条令', '二十七', '二', '0', '标志服饰佩带与本人身份不符或者不齐全', NULL, '批评教育，开具《军队人员（车辆）违纪违法通知单》后放行', '情节较重', NULL, '2');`,
  `INSERT INTO jbjl_czff (bh, zcmc, tm, kx, lx, qxms, qxjc, czff, yzcd, klwp, yzbs) VALUES ('2703', '军队警备条令', '二十七', '三', '0', '军服（文职人员服装）与便服混穿或者着仿制军服（文职人员服装）', NULL, '批评教育，开具《军队人员（车辆）违纪违法通知单》后放行', '情节较重', NULL, '2');`,
  `INSERT INTO jbjl_czff (bh, zcmc, tm, kx, lx, qxms, qxjc, czff, yzcd, klwp, yzbs) VALUES ('2704', '军队警备条令', '二十七', '四', '0', '使用非制式腰带、领带、围巾', NULL, '批评教育，开具《军队人员（车辆）违纪违法通知单》后放行', '情节较重', NULL, '2');`,
  `INSERT INTO jbjl_czff (bh, zcmc, tm, kx, lx, qxms, qxjc, czff, yzcd, klwp, yzbs) VALUES ('2705', '军队警备条令', '二十七', '五', '0', '外着制式毛衣（绒衣）', NULL, '批评教育，开具《军队人员（车辆）违纪违法通知单》后放行', '情节较重', NULL, '2');`,
  `INSERT INTO jbjl_czff (bh, zcmc, tm, kx, lx, qxms, qxjc, czff, yzcd, klwp, yzbs) VALUES ('2706', '军队警备条令', '二十七', '六', '0', '头发和胡须不符合规定或者化浓妆、染指甲', NULL, '批评教育，开具《军队人员（车辆）违纪违法通知单》后放行', '情节较重', NULL, '2');`,
  `INSERT INTO jbjl_czff (bh, zcmc, tm, kx, lx, qxms, qxjc, czff, yzcd, klwp, yzbs) VALUES ('2707', '军队警备条令', '二十七', '七', '0', '穿鞋、袜不符合规定或者穿拖鞋、赤脚穿鞋', NULL, '批评教育，开具《军队人员（车辆）违纪违法通知单》后放行', '情节较重', NULL, '2');`,
  `INSERT INTO jbjl_czff (bh, zcmc, tm, kx, lx, qxms, qxjc, czff, yzcd, klwp, yzbs) VALUES ('2708', '军队警备条令', '二十七', '八', '0', '猥集街头、嬉戏打闹、举止不端', NULL, '批评教育，开具《军队人员（车辆）违纪违法通知单》后放行', '情节较重', NULL, '2');`,
  `INSERT INTO jbjl_czff (bh, zcmc, tm, kx, lx, qxms, qxjc, czff, yzcd, klwp, yzbs) VALUES ('2709', '军队警备条令', '二十七', '九', '0', '未随身携带军队人员身份证件', NULL, '批评教育，开具《军队人员（车辆）违纪违法通知单》后放行', '情节较重', NULL, '2');`,
  `INSERT INTO jbjl_czff (bh, zcmc, tm, kx, lx, qxms, qxjc, czff, yzcd, klwp, yzbs) VALUES ('2710', '军队警备条令', '二十七', '十', '0', '其他违反军容风纪情节较重', NULL, '批评教育，开具《军队人员（车辆）违纪违法通知单》后放行', '情节较重', NULL, '2');`,
  `INSERT INTO jbjl_czff (bh, zcmc, tm, kx, lx, qxms, qxjc, czff, yzcd, klwp, yzbs) VALUES ('2801', '军队警备条令', '二十八', '一', '0', '参与宗教、迷信活动', '宗教迷信', '立即制止，并予以盘问', '情节严重', NULL, '3');`,
  `INSERT INTO jbjl_czff (bh, zcmc, tm, kx, lx, qxms, qxjc, czff, yzcd, klwp, yzbs) VALUES ('2802', '军队警备条令', '二十八', '二', '0', '围观和参与社会游行、示威、静坐', '游行示威静坐', '立即制止，并予以盘问', '情节严重', NULL, '3');`,
  `INSERT INTO jbjl_czff (bh, zcmc, tm, kx, lx, qxms, qxjc, czff, yzcd, klwp, yzbs) VALUES ('2803', '军队警备条令', '二十八', '三', '0', '打架斗殴、酗酒滋事等扰乱公共秩序', '扰乱公共秩序', '立即制止，并予以盘问', '情节严重', NULL, '3');`,
  `INSERT INTO jbjl_czff (bh, zcmc, tm, kx, lx, qxms, qxjc, czff, yzcd, klwp, yzbs) VALUES ('2804', '军队警备条令', '二十八', '四', '0', '违反规定携带武器、弹药或者其他军用物资', '违规携带军用物资', '立即制止，并予以盘问', '情节严重', NULL, '3');`,
  `INSERT INTO jbjl_czff (bh, zcmc, tm, kx, lx, qxms, qxjc, czff, yzcd, klwp, yzbs) VALUES ('2805', '军队警备条令', '二十八', '五', '0', '违反规定携带易燃、易爆等危险物品或者管制刀具', '违规携带危险物品', '立即制止，并予以盘问', '情节严重', NULL, '3');`,
  `INSERT INTO jbjl_czff (bh, zcmc, tm, kx, lx, qxms, qxjc, czff, yzcd, klwp, yzbs) VALUES ('2806', '军队警备条令', '二十八', '六', '0', '出租、出售军用牌证或者私自变卖军用物资', '变卖军用物资', '立即制止，并予以盘问', '情节严重', NULL, '3');`,
  `INSERT INTO jbjl_czff (bh, zcmc, tm, kx, lx, qxms, qxjc, czff, yzcd, klwp, yzbs) VALUES ('2807', '军队警备条令', '二十八', '七', '0', '携带、观看、传播、制作、贩卖淫秽物品', '淫秽物品', '立即制止，并予以盘问', '情节严重', NULL, '3');`,
  `INSERT INTO jbjl_czff (bh, zcmc, tm, kx, lx, qxms, qxjc, czff, yzcd, klwp, yzbs) VALUES ('2808', '军队警备条令', '二十八', '八', '0', '参与不健康消费娱乐活动', '不健康消费娱乐', '立即制止，并予以盘问', '情节严重', NULL, '3');`,
  `INSERT INTO jbjl_czff (bh, zcmc, tm, kx, lx, qxms, qxjc, czff, yzcd, klwp, yzbs) VALUES ('2809', '军队警备条令', '二十八', '九', '0', '在接受检查纠察时拒不出示证件或者以侮辱、谩骂、殴打等方式妨碍警备工作人员执勤', '妨碍警备执勤', '立即制止，并予以盘问', '情节严重', NULL, '3');`,
  `INSERT INTO jbjl_czff (bh, zcmc, tm, kx, lx, qxms, qxjc, czff, yzcd, klwp, yzbs) VALUES ('2810', '军队警备条令', '二十八', '十', '0', '其他违纪违法情节严重', '其他严重情节', '立即制止，并予以盘问', '情节严重', NULL, '3');`,
  `INSERT INTO jbjl_czff (bh, zcmc, tm, kx, lx, qxms, qxjc, czff, yzcd, klwp, yzbs) VALUES ('3201', '军队警备条令', '三十二', '一', '1', '车容不整', NULL, '批评教育，令其纠正后放行', '情节轻微', NULL, '0');`,
  `INSERT INTO jbjl_czff (bh, zcmc, tm, kx, lx, qxms, qxjc, czff, yzcd, klwp, yzbs) VALUES ('3202', '军队警备条令', '三十二', '二', '1', '驾驶室前后挡风玻璃范围内悬挂、摆放物品', NULL, '批评教育，令其纠正后放行', '情节轻微', NULL, '0');`,
  `INSERT INTO jbjl_czff (bh, zcmc, tm, kx, lx, qxms, qxjc, czff, yzcd, klwp, yzbs) VALUES ('3203', '军队警备条令', '三十二', '三', '1', '驾乘人员在车辆行驶中未按规定使用安全带', NULL, '批评教育，令其纠正后放行', '情节轻微', NULL, '0');`,
  `INSERT INTO jbjl_czff (bh, zcmc, tm, kx, lx, qxms, qxjc, czff, yzcd, klwp, yzbs) VALUES ('3204', '军队警备条令', '三十二', '四', '1', '车辆行驶中驾驶员拨打、接听手持电话', NULL, '批评教育，令其纠正后放行', '情节轻微', NULL, '0');`,
  `INSERT INTO jbjl_czff (bh, zcmc, tm, kx, lx, qxms, qxjc, czff, yzcd, klwp, yzbs) VALUES ('3205', '军队警备条令', '三十二', '五', '1', '违反道路交通安全法规停放车辆', NULL, '批评教育，令其纠正后放行', '情节轻微', NULL, '0');`,
  `INSERT INTO jbjl_czff (bh, zcmc, tm, kx, lx, qxms, qxjc, czff, yzcd, klwp, yzbs) VALUES ('3206', '军队警备条令', '三十二', '六', '1', '其他军车违纪违法情节轻微且能够现场纠正', NULL, '批评教育，令其纠正后放行', '情节轻微', NULL, '0');`,
  `INSERT INTO jbjl_czff (bh, zcmc, tm, kx, lx, qxms, qxjc, czff, yzcd, klwp, yzbs) VALUES ('3301', '军队警备条令', '三十三', '一', '1', '驾驶证、行车执照无审验合格戳记', NULL, '批评教育，扣留驾驶证，开具《军队人员（车辆）违纪违法通知单》后放行', '情节较轻', '驾驶证', '1');`,
  `INSERT INTO jbjl_czff (bh, zcmc, tm, kx, lx, qxms, qxjc, czff, yzcd, klwp, yzbs) VALUES ('3302', '军队警备条令', '三十三', '二', '1', '违反规定占用公交车道，占用应急车道和非机动车道', NULL, '批评教育，扣留驾驶证，开具《军队人员（车辆）违纪违法通知单》后放行', '情节较轻', '驾驶证', '1');`,
  `INSERT INTO jbjl_czff (bh, zcmc, tm, kx, lx, qxms, qxjc, czff, yzcd, klwp, yzbs) VALUES ('3303', '军队警备条令', '三十三', '三', '1', '实习驾驶员不按照规定驾驶机动车', NULL, '批评教育，扣留驾驶证，开具《军队人员（车辆）违纪违法通知单》后放行', '情节较轻', '驾驶证', '1');`,
  `INSERT INTO jbjl_czff (bh, zcmc, tm, kx, lx, qxms, qxjc, czff, yzcd, klwp, yzbs) VALUES ('3304', '军队警备条令', '三十三', '四', '1', '试车未悬挂试车号牌或者拖挂车未悬挂拖挂车号牌', NULL, '批评教育，扣留驾驶证，开具《军队人员（车辆）违纪违法通知单》后放行', '情节较轻', '驾驶证', '1');`,
  `INSERT INTO jbjl_czff (bh, zcmc, tm, kx, lx, qxms, qxjc, czff, yzcd, klwp, yzbs) VALUES ('3305', '军队警备条令', '三十三', '五', '1', '未携带三角警告牌、处于有效期内的灭火器等驾驶安全设施', NULL, '批评教育，扣留驾驶证，开具《军队人员（车辆）违纪违法通知单》后放行', '情节较轻', '驾驶证', '1');`,
  `INSERT INTO jbjl_czff (bh, zcmc, tm, kx, lx, qxms, qxjc, czff, yzcd, klwp, yzbs) VALUES ('3306', '军队警备条令', '三十三', '六', '1', '摩托车驾乘人员未按规定戴安全头盔', NULL, '批评教育，扣留驾驶证，开具《军队人员（车辆）违纪违法通知单》后放行', '情节较轻', '驾驶证', '1');`,
  `INSERT INTO jbjl_czff (bh, zcmc, tm, kx, lx, qxms, qxjc, czff, yzcd, klwp, yzbs) VALUES ('3307', '军队警备条令', '三十三', '七', '1', '其他军车违纪违法情节较轻', NULL, '批评教育，扣留驾驶证，开具《军队人员（车辆）违纪违法通知单》后放行', '情节较轻', '驾驶证', '1');`,
  `INSERT INTO jbjl_czff (bh, zcmc, tm, kx, lx, qxms, qxjc, czff, yzcd, klwp, yzbs) VALUES ('3401', '军队警备条令', '三十四', '一', '1', '车辆喷涂、安装、张贴规定以外标志', NULL, '批评教育，扣留车辆和驾驶证，开具《军队人员（车辆）违纪违法通知单》后放行', '情节较重', '车辆和驾驶证', '2');`,
  `INSERT INTO jbjl_czff (bh, zcmc, tm, kx, lx, qxms, qxjc, czff, yzcd, klwp, yzbs) VALUES ('3402', '军队警备条令', '三十四', '二', '1', '故意遮挡、无损、不按照规定安装号牌', NULL, '批评教育，扣留车辆和驾驶证，开具《军队人员（车辆）违纪违法通知单》后放行', '情节较重', '车辆和驾驶证', '2');`,
  `INSERT INTO jbjl_czff (bh, zcmc, tm, kx, lx, qxms, qxjc, czff, yzcd, klwp, yzbs) VALUES ('3403', '军队警备条令', '三十四', '三', '1', '无车辆派遣凭证，私自出车', NULL, '批评教育，扣留车辆和驾驶证，开具《军队人员（车辆）违纪违法通知单》后放行', '情节较重', '车辆和驾驶证', '2');`,
  `INSERT INTO jbjl_czff (bh, zcmc, tm, kx, lx, qxms, qxjc, czff, yzcd, klwp, yzbs) VALUES ('3404', '军队警备条令', '三十四', '四', '1', '所驾车辆与驾驶证准驾车型不符', NULL, '批评教育，扣留车辆和驾驶证，开具《军队人员（车辆）违纪违法通知单》后放行', '情节较重', '车辆和驾驶证', '2');`,
  `INSERT INTO jbjl_czff (bh, zcmc, tm, kx, lx, qxms, qxjc, czff, yzcd, klwp, yzbs) VALUES ('3405', '军队警备条令', '三十四', '五', '1', '违反规定安装或者使用警报器、警灯', NULL, '批评教育，扣留车辆和驾驶证，开具《军队人员（车辆）违纪违法通知单》后放行', '情节较重', '车辆和驾驶证', '2');`,
  `INSERT INTO jbjl_czff (bh, zcmc, tm, kx, lx, qxms, qxjc, czff, yzcd, klwp, yzbs) VALUES ('3406', '军队警备条令', '三十四', '六', '1', '其他军车违纪违法情节较重', NULL, '批评教育，扣留车辆和驾驶证，开具《军队人员（车辆）违纪违法通知单》后放行', '情节较重', '车辆和驾驶证', '2');`,
  `INSERT INTO jbjl_czff (bh, zcmc, tm, kx, lx, qxms, qxjc, czff, yzcd, klwp, yzbs) VALUES ('3501', '军队警备条令', '三十五', '一', '1', '无证驾驶或者车辆无行车执照', '无证驾驶或无行车执照', '扣留车辆和驾驶证，予以盘问，开具《军队人员（车辆）违纪违法通知单》', '情节恶劣', '车辆和驾驶证', '3');`,
  `INSERT INTO jbjl_czff (bh, zcmc, tm, kx, lx, qxms, qxjc, czff, yzcd, klwp, yzbs) VALUES ('3502', '军队警备条令', '三十五', '二', '1', '行车执照与车辆、号牌信息不符', '车证不符', '扣留车辆和驾驶证，予以盘问，开具《军队人员（车辆）违纪违法通知单》', '情节恶劣', '车辆和驾驶证', '3');`,
  `INSERT INTO jbjl_czff (bh, zcmc, tm, kx, lx, qxms, qxjc, czff, yzcd, klwp, yzbs) VALUES ('3503', '军队警备条令', '三十五', '三', '1', '未悬挂车辆号牌或者使用过期号牌、非制式号牌', '无效号牌', '扣留车辆和驾驶证，予以盘问，开具《军队人员（车辆）违纪违法通知单》', '情节恶劣', '车辆和驾驶证', '3');`,
  `INSERT INTO jbjl_czff (bh, zcmc, tm, kx, lx, qxms, qxjc, czff, yzcd, klwp, yzbs) VALUES ('3504', '军队警备条令', '三十五', '四', '1', '酒驾醉驾、毒驾或者涉嫌交通肇事逃逸', '酒驾醉驾毒驾或肇事逃逸', '扣留车辆和驾驶证，予以盘问，开具《军队人员（车辆）违纪违法通知单》', '情节恶劣', '车辆和驾驶证', '3');`,
  `INSERT INTO jbjl_czff (bh, zcmc, tm, kx, lx, qxms, qxjc, czff, yzcd, klwp, yzbs) VALUES ('3505', '军队警备条令', '三十五', '五', '1', '车况不良或者违反乘载规定，危及行车安全', '危及行车安全', '扣留车辆和驾驶证，予以盘问，开具《军队人员（车辆）违纪违法通知单》', '情节恶劣', '车辆和驾驶证', '3');`,
  `INSERT INTO jbjl_czff (bh, zcmc, tm, kx, lx, qxms, qxjc, czff, yzcd, klwp, yzbs) VALUES ('3506', '军队警备条令', '三十五', '六', '1', '利用军车从事营业性运输活动或者帮助他人运送物品收取酬劳', '利用军车获利', '扣留车辆和驾驶证，予以盘问，开具《军队人员（车辆）违纪违法通知单》', '情节恶劣', '车辆和驾驶证', '3');`,
  `INSERT INTO jbjl_czff (bh, zcmc, tm, kx, lx, qxms, qxjc, czff, yzcd, klwp, yzbs) VALUES ('3507', '军队警备条令', '三十五', '七', '1', '涉嫌利用军车进行走私、贩毒、盗抢等违法活动', '走私贩毒盗抢', '扣留车辆和驾驶证，予以盘问，开具《军队人员（车辆）违纪违法通知单》', '情节恶劣', '车辆和驾驶证', '3');`,
  `INSERT INTO jbjl_czff (bh, zcmc, tm, kx, lx, qxms, qxjc, czff, yzcd, klwp, yzbs) VALUES ('3508', '军队警备条令', '三十五', '八', '1', '在接受检查纠察时拒不出示证件或者以侮辱、谩骂、殴打等方式妨碍警备工作人员执勤', '妨碍警备执勤', '扣留车辆和驾驶证，予以盘问，开具《军队人员（车辆）违纪违法通知单》', '情节恶劣', '车辆和驾驶证', '3');`,
  `INSERT INTO jbjl_czff (bh, zcmc, tm, kx, lx, qxms, qxjc, czff, yzcd, klwp, yzbs) VALUES ('3509', '军队警备条令', '三十五', '九', '1', '其他军车违纪违法情节恶劣', '其他恶劣情节', '扣留车辆和驾驶证，予以盘问，开具《军队人员（车辆）违纪违法通知单》', '情节恶劣', '车辆和驾驶证', '3');`
];

export const xxsz_data = [`INSERT INTO XXSZ (id, status) VALUES ('1', '1');`]
